"use client";
import "./globals.css";
import Providers from "./utils/providers";

export const metadata = {
  title: "Win Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
